"""Tests for Gitea DevOps tools."""

from unittest.mock import AsyncMock, patch

import httpx
import pytest
from fastmcp import FastMCP

import config
from lib.gitea import parse_renovate_body
from tests.conftest import count_tools, get_tool_fn, make_mock_ctx, make_response
from tools import gitea

# --- Helpers ---


# --- Mock data ---

MOCK_REPOS_SEARCH = {
    "data": [
        {
            "name": "homelab-mcp",
            "full_name": "org/homelab-mcp",
            "description": "MCP server",
            "html_url": "http://gitea/org/homelab-mcp",
            "stars_count": 0,
            "forks_count": 0,
            "open_issues_count": 2,
            "updated_at": "2026-04-01T00:00:00Z",
        },
        {
            "name": "dotfiles",
            "full_name": "user/dotfiles",
            "description": "Personal dotfiles",
            "html_url": "http://gitea/user/dotfiles",
            "stars_count": 1,
            "forks_count": 0,
            "open_issues_count": 0,
            "updated_at": "2026-03-15T00:00:00Z",
        },
    ],
    "ok": True,
}

MOCK_PRS = [
    {
        "number": 1,
        "title": "chore(deps): update dependency X",
        "state": "open",
        "user": {"login": "renovate"},
        "created_at": "2026-04-01T00:00:00Z",
        "updated_at": "2026-04-02T00:00:00Z",
        "labels": [{"name": "dependencies"}],
    },
    {
        "number": 2,
        "title": "feat: add new feature",
        "state": "open",
        "user": {"login": "jon"},
        "created_at": "2026-04-01T12:00:00Z",
        "updated_at": "2026-04-02T12:00:00Z",
        "labels": [],
    },
]

MOCK_CI_RUNS = {
    "workflow_runs": [
        {
            "id": 100,
            "name": "CI",
            "status": "completed",
            "conclusion": "success",
            "created_at": "2026-04-02T10:00:00Z",
            "updated_at": "2026-04-02T10:05:00Z",
            "event": "push",
        },
        {
            "id": 99,
            "name": "CI",
            "status": "completed",
            "conclusion": "failure",
            "created_at": "2026-04-01T10:00:00Z",
            "updated_at": "2026-04-01T10:05:00Z",
            "event": "push",
        },
    ]
}


# Real Renovate PR body (docker-stacks #178): docker-tag bump, no release notes.
RENOVATE_BODY_NO_NOTES = """This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| maximhq/bifrost | major | `v1.6.4` -> `2.1.29` |

---

### Configuration

📅 **Schedule**: Branch creation - "" (UTC).

This PR has been generated by [Mend Renovate](https://github.com/renovatebot/renovate).
"""

# Real Renovate PR body (docker-stacks #177): notes skipped (no github.com creds),
# package cell carries a "(source)" link suffix.
RENOVATE_BODY_SKIPPED = """This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [linuxserver/mariadb](https://ghcr.io) ([source](https://github.com/x/y)) | minor | `11.4.12` -> `11.8.8` |

> [!IMPORTANT]
> Release Notes retrieval for this PR were skipped because no github.com credentials were available.

---

### Configuration

This PR has been generated by [Mend Renovate](https://github.com/renovatebot/renovate).
"""

# Synthetic body with a real Release Notes section (once Renovate is credentialed).
RENOVATE_BODY_WITH_NOTES = """This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| some/app | patch | `1.2.0` -> `1.2.1` |

---

### Release Notes

<details>
<summary>some/app (v1.2.1)</summary>

Fixed a nasty bug in the widget loader.
Improved startup time.

</details>

---

### Configuration

📅 **Schedule**: at any time.
"""

# Renovate image-update PRs as returned by the /pulls list (with body + head.sha).
MOCK_IMAGE_PRS = [
    {
        "number": 178,
        "title": "chore(deps): update maximhq/bifrost docker tag to v2",
        "state": "open",
        "user": {"login": "renovate-bot"},
        "html_url": "http://gitea/youruser/docker-stacks/pulls/178",
        "created_at": "2026-07-15T00:00:00Z",
        "updated_at": "2026-07-17T00:00:00Z",
        "labels": [],
        "head": {"sha": "deadbeef"},
        "body": RENOVATE_BODY_NO_NOTES,
    },
    {
        "number": 42,
        "title": "feat: a human PR",
        "state": "open",
        "user": {"login": "jon"},
        "html_url": "http://gitea/youruser/docker-stacks/pulls/42",
        "created_at": "2026-07-15T00:00:00Z",
        "updated_at": "2026-07-16T00:00:00Z",
        "labels": [],
        "head": {"sha": "cafef00d"},
        "body": "just a normal change",
    },
]


@pytest.fixture
def mcp_app():
    """FastMCP with Gitea tools registered (mirrors test_docker's pattern)."""
    app = FastMCP("test")
    with (
        patch.object(config, "GITEA_URL", "http://gitea:7850"),
        patch.object(config, "GITEA_TOKEN", "test-token"),
    ):
        gitea.register(app)
    return app


# --- Tests ---


@pytest.mark.asyncio
async def test_gitea_conditional_registration():
    """Tools are not registered when GITEA_URL is not set."""
    app = FastMCP("test")
    with (
        patch.object(config, "GITEA_URL", None),
        patch.object(config, "GITEA_TOKEN", None),
    ):
        gitea.register(app)
    assert count_tools(app) == 0


@pytest.mark.asyncio
async def test_gitea_registers_5_tools(mcp_app):
    """register() creates 5 tools when credentials are set."""
    assert count_tools(mcp_app) == 5


@pytest.mark.asyncio
async def test_gitea_repos(mcp_app):
    """get_gitea_repos returns formatted repo list."""
    mock_client = AsyncMock()
    mock_client.get = AsyncMock(return_value=make_response(MOCK_REPOS_SEARCH))
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_repos")
    result = await fn(ctx)

    assert result["repo_count"] == 2
    assert result["repos"][0]["name"] == "homelab-mcp"
    assert result["repos"][0]["full_name"] == "org/homelab-mcp"
    assert result["repos"][0]["url"] == "http://gitea/org/homelab-mcp"
    assert result["repos"][0]["open_issues"] == 2
    assert result["repos"][1]["name"] == "dotfiles"


@pytest.mark.asyncio
async def test_gitea_repos_api_error(mcp_app):
    """get_gitea_repos returns error dict on API failure."""
    mock_client = AsyncMock()
    mock_client.get = AsyncMock(
        side_effect=httpx.HTTPStatusError(
            "Server Error",
            request=httpx.Request("GET", "http://test"),
            response=httpx.Response(500),
        )
    )
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_repos")
    result = await fn(ctx)

    assert result["error"] == "http_error"
    assert result["status"] == 500


@pytest.mark.asyncio
async def test_gitea_repos_timeout(mcp_app):
    """A timeout is reported as 'timeout', not a generic connection_error.

    Regression for the shared lib.http adoption: gitea's old _get caught bare
    Exception and mislabeled every timeout as connection_error.
    """
    mock_client = AsyncMock()
    mock_client.get = AsyncMock(side_effect=httpx.TimeoutException("timed out"))
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_repos")
    result = await fn(ctx)

    assert result["error"] == "timeout"


@pytest.mark.asyncio
async def test_gitea_repos_connection_error(mcp_app):
    """A transport-level failure surfaces {'error': 'connection_error'}."""
    mock_client = AsyncMock()
    mock_client.get = AsyncMock(side_effect=httpx.ConnectError("refused"))
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_repos")
    result = await fn(ctx)

    assert result["error"] == "connection_error"


@pytest.mark.asyncio
async def test_gitea_pull_requests_with_repo(mcp_app):
    """get_gitea_pull_requests with repo param returns PRs for that repo."""
    mock_client = AsyncMock()
    mock_client.get = AsyncMock(return_value=make_response(MOCK_PRS))
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_pull_requests")
    result = await fn(ctx, repo="org/homelab-mcp")

    assert result["pr_count"] == 2
    # Renovate PR is included
    assert result["pull_requests"][0]["title"] == "chore(deps): update dependency X"
    assert result["pull_requests"][0]["author"] == "renovate"
    assert result["pull_requests"][0]["labels"] == ["dependencies"]


@pytest.mark.asyncio
async def test_gitea_pull_requests_cross_repo(mcp_app):
    """get_gitea_pull_requests without repo param does cross-repo aggregation."""
    mock_client = AsyncMock()

    def side_effect(path, params=None):
        if "/repos/search" in path:
            return make_response(MOCK_REPOS_SEARCH)
        elif "/pulls" in path:
            return make_response(MOCK_PRS)
        return make_response([])

    mock_client.get = AsyncMock(side_effect=side_effect)
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_pull_requests")
    result = await fn(ctx)

    # 2 repos x 2 PRs each = 4 total
    assert result["pr_count"] == 4


@pytest.mark.asyncio
async def test_gitea_pull_requests_empty(mcp_app):
    """get_gitea_pull_requests returns pr_count=0 when no PRs."""
    mock_client = AsyncMock()
    mock_client.get = AsyncMock(return_value=make_response([]))
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_pull_requests")
    result = await fn(ctx, repo="org/homelab-mcp")

    assert result["pr_count"] == 0
    assert result["pull_requests"] == []


@pytest.mark.asyncio
async def test_gitea_ci_runs(mcp_app):
    """get_gitea_ci_runs returns sorted runs with limit."""
    mock_client = AsyncMock()

    def side_effect(path, params=None):
        if "/repos/search" in path:
            return make_response(MOCK_REPOS_SEARCH)
        elif "/actions/runs" in path:
            return make_response(MOCK_CI_RUNS)
        return make_response({"workflow_runs": []})

    mock_client.get = AsyncMock(side_effect=side_effect)
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_ci_runs")
    result = await fn(ctx, limit=3)

    assert result["run_count"] == 3
    # Sorted by created_at desc: 2026-04-02 first
    assert result["runs"][0]["created"] == "2026-04-02T10:00:00Z"


@pytest.mark.asyncio
async def test_gitea_ci_runs_per_repo_limit_tracks_limit(mcp_app):
    """Regression (item 19): the per-repo fetch limit follows the `limit`
    argument (capped) instead of a hardcoded 5, so a busy repo's recent runs
    are not dropped before the global sort."""
    captured = {}
    mock_client = AsyncMock()

    def side_effect(path, params=None):
        if "/repos/search" in path:
            return make_response(MOCK_REPOS_SEARCH)
        elif "/actions/runs" in path:
            captured["limit"] = (params or {}).get("limit")
            return make_response(MOCK_CI_RUNS)
        return make_response({"workflow_runs": []})

    mock_client.get = AsyncMock(side_effect=side_effect)
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_ci_runs")
    await fn(ctx, limit=20)

    assert captured["limit"] == 20


@pytest.mark.asyncio
async def test_gitea_ci_runs_403_graceful(mcp_app):
    """get_gitea_ci_runs handles 403 gracefully (skip repo, don't crash)."""
    mock_client = AsyncMock()

    def side_effect(path, params=None):
        if "/repos/search" in path:
            return make_response(MOCK_REPOS_SEARCH)
        elif "/actions/runs" in path:
            raise httpx.HTTPStatusError(
                "Forbidden",
                request=httpx.Request("GET", "http://test"),
                response=httpx.Response(403),
            )
        return make_response({"workflow_runs": []})

    mock_client.get = AsyncMock(side_effect=side_effect)
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_ci_runs")
    result = await fn(ctx)

    # Should not crash, returns empty runs
    assert result["run_count"] == 0
    assert result["runs"] == []


@pytest.mark.asyncio
async def test_gitea_ci_runs_custom_limit(mcp_app):
    """get_gitea_ci_runs respects custom limit parameter."""
    mock_client = AsyncMock()

    def side_effect(path, params=None):
        if "/repos/search" in path:
            return make_response(MOCK_REPOS_SEARCH)
        elif "/actions/runs" in path:
            return make_response(MOCK_CI_RUNS)
        return make_response({"workflow_runs": []})

    mock_client.get = AsyncMock(side_effect=side_effect)
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_gitea_ci_runs")
    result = await fn(ctx, limit=1)

    assert result["run_count"] == 1
    assert len(result["runs"]) == 1


# --- parse_renovate_body (pure) ---


def test_parse_renovate_body_single_no_notes():
    """Docker-tag bump: one update parsed, v-prefix normalized, no notes."""
    parsed = parse_renovate_body(RENOVATE_BODY_NO_NOTES)
    assert parsed["release_notes"] is None
    assert parsed["updates"] == [
        {
            "package": "maximhq/bifrost",
            "update_type": "major",
            "current": "1.6.4",
            "proposed": "2.1.29",
        }
    ]


def test_parse_renovate_body_skipped_notes_and_source_suffix():
    """Package link + '(source)' suffix stripped; skip-notice -> release_notes None."""
    parsed = parse_renovate_body(RENOVATE_BODY_SKIPPED)
    assert parsed["release_notes"] is None
    assert parsed["updates"] == [
        {
            "package": "linuxserver/mariadb",
            "update_type": "minor",
            "current": "11.4.12",
            "proposed": "11.8.8",
        }
    ]


def test_parse_renovate_body_with_notes():
    """A real Release Notes section is captured and bounded before Configuration."""
    parsed = parse_renovate_body(RENOVATE_BODY_WITH_NOTES)
    assert parsed["updates"][0]["package"] == "some/app"
    assert parsed["release_notes"] is not None
    assert "Fixed a nasty bug" in parsed["release_notes"]
    assert "Configuration" not in parsed["release_notes"]
    assert "<summary>" not in parsed["release_notes"]  # HTML chrome stripped


def test_parse_renovate_body_empty():
    """A blank/None body yields no updates and no notes (never raises)."""
    assert parse_renovate_body("") == {"updates": [], "release_notes": None}
    assert parse_renovate_body("nothing structured here")["updates"] == []


# --- get_image_updates ---


@pytest.mark.asyncio
async def test_get_image_updates_default_repo(mcp_app):
    """Defaults to docker-stacks, keeps only Renovate PRs, enriches each."""
    mock_client = AsyncMock()

    def side_effect(path, params=None):
        if "/commits/" in path:
            return make_response(
                {
                    "state": "success",
                    "total_count": 1,
                    "statuses": [{"state": "success"}],
                }
            )
        if path.endswith("/pulls"):
            return make_response(MOCK_IMAGE_PRS)
        return make_response({})

    mock_client.get = AsyncMock(side_effect=side_effect)
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_image_updates")
    result = await fn(ctx)

    # Human PR #42 filtered out; only the renovate-bot PR remains.
    assert result["update_count"] == 1
    item = result["image_updates"][0]
    assert item["number"] == 178
    assert item["repo"] == config.STACKS_REPO
    assert item["ci_status"] == "success"
    assert item["release_notes"] is None
    assert item["updates"][0] == {
        "package": "maximhq/bifrost",
        "update_type": "major",
        "current": "1.6.4",
        "proposed": "2.1.29",
    }


@pytest.mark.asyncio
async def test_get_image_updates_upstream_error(mcp_app):
    """A failed /pulls fetch propagates the error dict."""
    mock_client = AsyncMock()
    mock_client.get = AsyncMock(
        side_effect=httpx.HTTPStatusError(
            "boom",
            request=httpx.Request("GET", "http://test"),
            response=httpx.Response(500),
        )
    )
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "get_image_updates")
    result = await fn(ctx)

    assert result["error"] == "http_error"
    assert result["status"] == 500


# --- apply_image_update (WRITE) ---


def _pull(mergeable=True, state="open", merged=False, sha="deadbeef"):
    return {
        "number": 178,
        "title": "chore(deps): update maximhq/bifrost docker tag to v2",
        "state": state,
        "merged": merged,
        "mergeable": mergeable,
        "head": {"sha": sha},
        "body": RENOVATE_BODY_NO_NOTES,
    }


def _apply_ctx(mergeable=True, state="open", merged=False, ci_state="success"):
    """Mock ctx whose GET serves the PR and its combined CI status."""
    mock_client = AsyncMock()

    def get_side_effect(path, params=None):
        if "/commits/" in path:
            if ci_state == "none":
                # Gitea's no-checks response: pending state, zero statuses.
                return make_response(
                    {"state": "pending", "total_count": 0, "statuses": None}
                )
            return make_response(
                {"state": ci_state, "total_count": 1, "statuses": [{"state": ci_state}]}
            )
        return make_response(_pull(mergeable=mergeable, state=state, merged=merged))

    mock_client.get = AsyncMock(side_effect=get_side_effect)
    mock_client.post = AsyncMock(return_value=make_response(None, status_code=200))
    return make_mock_ctx(gitea=mock_client), mock_client


@pytest.mark.asyncio
async def test_apply_image_update_success(mcp_app):
    """Merges with a merge commit and reports success (default repo)."""
    ctx, mock_client = _apply_ctx()

    fn = get_tool_fn(mcp_app, "apply_image_update")
    result = await fn(ctx, pr_number=178)

    merge_call = mock_client.post.await_args
    assert merge_call.args[0].endswith("/pulls/178/merge")
    assert merge_call.kwargs["json"] == {"Do": "merge"}
    assert result["merged"] is True
    assert result["result"] == "success"
    assert result["repo"] == config.STACKS_REPO
    assert "_meta" in result


@pytest.mark.asyncio
async def test_apply_image_update_dry_run(mcp_app):
    """Dry run previews would_merge/ci_status and never POSTs."""
    ctx, mock_client = _apply_ctx()

    fn = get_tool_fn(mcp_app, "apply_image_update")
    result = await fn(ctx, pr_number=178, dry_run=True)

    mock_client.post.assert_not_awaited()
    assert result["dry_run"] is True
    assert result["would_merge"] is True
    assert result["ci_status"] == "success"
    assert result["updates"][0]["package"] == "maximhq/bifrost"


@pytest.mark.asyncio
async def test_apply_image_update_no_ci_merges(mcp_app):
    """Gitea's zero-status 'pending' (no checks) is treated as none, not blocking."""
    ctx, mock_client = _apply_ctx(ci_state="none")

    fn = get_tool_fn(mcp_app, "apply_image_update")
    dr = await fn(ctx, pr_number=178, dry_run=True)
    assert dr["ci_status"] == "none"
    assert dr["would_merge"] is True

    result = await fn(ctx, pr_number=178)
    mock_client.post.assert_awaited_once()
    assert result["merged"] is True


@pytest.mark.asyncio
async def test_apply_image_update_ci_failing_blocks(mcp_app):
    """Failing CI blocks the merge unless force=True."""
    ctx, mock_client = _apply_ctx(ci_state="failure")

    fn = get_tool_fn(mcp_app, "apply_image_update")
    result = await fn(ctx, pr_number=178)

    mock_client.post.assert_not_awaited()
    assert result["error"] == "ci_failing"


@pytest.mark.asyncio
async def test_apply_image_update_force_overrides_ci(mcp_app):
    """force=True merges even when CI is failing."""
    ctx, mock_client = _apply_ctx(ci_state="failure")

    fn = get_tool_fn(mcp_app, "apply_image_update")
    result = await fn(ctx, pr_number=178, force=True)

    mock_client.post.assert_awaited_once()
    assert result["merged"] is True


@pytest.mark.asyncio
async def test_apply_image_update_conflict(mcp_app):
    """A non-mergeable (conflicting) PR is refused, no POST."""
    ctx, mock_client = _apply_ctx(mergeable=False)

    fn = get_tool_fn(mcp_app, "apply_image_update")
    result = await fn(ctx, pr_number=178)

    mock_client.post.assert_not_awaited()
    assert result["error"] == "conflict"


@pytest.mark.asyncio
async def test_apply_image_update_not_open(mcp_app):
    """An already-merged / closed PR is refused, no POST."""
    ctx, mock_client = _apply_ctx(state="closed", merged=True)

    fn = get_tool_fn(mcp_app, "apply_image_update")
    result = await fn(ctx, pr_number=178)

    mock_client.post.assert_not_awaited()
    assert result["error"] == "not_open"


@pytest.mark.asyncio
async def test_apply_image_update_not_found(mcp_app):
    """A 404 on the PR fetch propagates as http_error, no POST."""
    mock_client = AsyncMock()
    mock_client.get = AsyncMock(
        side_effect=httpx.HTTPStatusError(
            "not found",
            request=httpx.Request("GET", "http://test"),
            response=httpx.Response(404),
        )
    )
    mock_client.post = AsyncMock()
    ctx = make_mock_ctx(gitea=mock_client)

    fn = get_tool_fn(mcp_app, "apply_image_update")
    result = await fn(ctx, pr_number=999)

    mock_client.post.assert_not_awaited()
    assert result["error"] == "http_error"
    assert result["status"] == 404
